name: Deploiement et test des PR
on:
  pull_request:
    branches:
      - main
env:
  DATABASE_URL: ${{ secrets.PARAM_DATABASE_URL }}
  JWT_SECRET: ${{ secrets.PARAM_JWT_SECRET }}
  APP_NAME: ${{ secrets.PARAM_APP_NAME }}
  REDIS_URI: ${{ secrets.PARAM_REDIS_URI }}
  NODE_ENV: ${{ secrets.PARAM_NODE_ENV }}

jobs:
  backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: back

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: 24
    - run: npm ci
    - run: npx prisma generate
    - run: npm run build
    - run: npm test